version: '3.8'

services:

  elastic:
    container_name: ${PROJECT_NAME}_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - node-name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 512mo HEAP
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${PROJECT_HOST}:9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: ${PROJECT_NAME}_kibana
    image: docker.elastic.co/kibana/kibana:8.3.2
    environment:
      - XPACK_SECURITY_ENABLED=false
      - ELASTICSEARCH_HOST=http://elastic:9200
    ports:
      - ${PROJECT_HOST}:5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "curl -s -I http://${PROJECT_HOST}:5601 | grep -q 'HTTP/1.1 302 Found'",
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 120
    depends_on:
      - elastic

volumes:
  esdata: {}
  kibanadata: {}
